[TempStyle]
StringAlign=Right
FontColor=#White#
FontSize=24
FontFace=#FontName#
AntiAlias=1
StringStyle=Bold

[TempStyleDec]
StringAlign=Right
FontColor=#White#
FontSize=18
FontFace=#FontName#
AntiAlias=1
StringStyle=Bold



[UseStyle]
StringAlign=Right
FontColor=#White#
FontSize=54
FontFace=#FontName#
AntiAlias=1

[UseStyleDec]
StringAlign=Right
FontColor=#White#
FontSize=36
FontFace=#FontName#
AntiAlias=1



[MemStyle]
StringAlign=Right
FontColor=#White#
FontSize=24
FontFace=#FontName#
AntiAlias=1
StringStyle=Bold



[GPUFanStyle]
StringAlign=Right
FontColor=#White#
FontSize=18
FontFace=#FontName#
AntiAlias=1
StringStyle=Bold



[HourStyle]
StringAlign=Left
FontColor=#White#
FontSize=96
FontFace=#FontName#
AntiAlias=1

[MinuteStyle]
StringAlign=Left
FontColor=#White#
FontSize=96
FontFace=#FontName#
AntiAlias=1